version: '3.8'

services:
  bankingsystem:
    image: bankingsystem
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Pa!55word"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"